export const FIXED_GALLERY_BOTTOM_NAVIGATION_HEIGHT = '56px';
export const GALLERY_MAX_WIDTH = '1600px';
export const SEARCH_DRAWER_BUTTON_ACTIONS_HEIGHT = '58.25px';
export const LANDSCAPE_PHOTO_SMALL_SCREEN_HEIGHT = '245.33px';
export const LANDSCAPE_PHOTO_LARGE_SCREEN_HEIGHT = '720px';
